### ISSUE TITLE
Clean system cache has no effect

### ISSUE THREAD

**Issue by kristinaking** [Mieze/RTL8111_driver_for_OS_X#52]
I have tried to reinstall 15.7 and 11, both of which are crashes

**Comment by Mieze** [comment]
You have to disable SIP first in order to able to clean system caches. It's also possible that your system has an ACPI related sleep/wake issue or that the driver has been damaged.

I have no reason to assume that there is anything wrong with the driver. Please fix your system! In case you need further assistance, post in insanelymac.com forums because I'm not accepting support requests on GitHub.
